source 'https://rubygems.org'
gem 'activerecord', require: 'active_record'
gem 'activesupport'
gem 'detect_language'
gem 'dotenv', require: 'dotenv/load'
gem 'ngram'
gem 'nokogiri'
gem 'pg'
gem 'pry'
gem 'puma'
gem 'rake'
gem 'require_all'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'slim'
